### ISSUE TITLE
Remove @Alexa 

### ISSUE THREAD

**Issue by MRSTLC123** [cakebarIO/QuickAdd-for-Todoist#17]
I know that you recently added the tag "@Alexa" to all items added to the list. This is feeling a bit cluttered and personally, I would prefer it not be there. I use Alexa to add items to my ToDoIst board to then stream to my Dakboard/home hub, so its a bit messy. Any way to remove this or have it be optional?

**Comment by cakebarIO** [comment]
I have included the @Alexa label because it was requested by many users, as it mimics the workflow from the original integration.

If anything changes with that respect, I can reopen this.

Additionally, I have an existing enhancement request to allow user defaults. If/once that is implemented, you may configure however you'd like.
