### ISSUE TITLE
Readme may be incorrect about due date when invoking using project. 

### ISSUE THREAD

**Issue by LiteTite** [cakebarIO/QuickAdd-for-Todoist#20]
Currently:

"Alexa, tell QuickAdd to add [task] to my [Todoist project name]" - Adds [task] with a default "today" due date to your custom Todoist Project. NOTE: The project name MUST contain no spaces (see below).

I believe you made the change to not set due dates by default if task is put into a custom project. yes?

**Comment by cakebarIO** [comment]
I did...I apologize for not updating this README. I have since removed the full list of features in this project...it will be used exclusively to log and track bugs/feature requests. For a full, up to date list of features, please visit https://www.erikrichter.com/project/quickadd-for-todoist-alexa-skill
