### ISSUE TITLE
Items added shouldn't include a due date by default.

### ISSUE THREAD

**Issue by bulawayo88** [cakebarIO/QuickAdd-for-Todoist#4]
I integrate with my calendar and now, when I add items with this skill they show up on my calendar because they have a today due date. 

Thanks for the skill!

**Comment by cakebarIO** [comment]
Removing the default “Today” would be easy...

However, during my development and testing process, I found that Alexa frequently misheard the spoken “today,” appending variations like “to day,” “day,” or “to” to the task without a date. This issue seemed specific to “today” and not to other dates like “tomorrow.” Additionally, with a misheard spoken “today,” Alexa also sometimes added items to the Alexa to-do list instead, which after July 1st won’t go to Todoist.

This led me to do some focus sessions…

Based off of the research I did, most people add the word “today” to their invocation and wanted it included…which, ultimately, is why I chose to add it. It also allows those who use Upcoming as their Home Screen, rather than Inbox, to see the tasks added without a lot of extra triage steps.

Additionally, the logic removes 2 extra syllables in the invocation that seemed redundant for a frequently-spoken workflow.

If I find, over time, more users prefer it not included, I will remove it!

In the meantime, I can understand how someone may not want a date on a task. I COULD add logic where if you say “no date,” or something similar, it would add the task without a date. Is that something you would appreciate? If so, what would be your ideal invocation for that?

**Comment by bulawayo88** [comment]
Ahhh. Makes sense and thanks for the explanation. I’m happy with the saying “no date” addition. It solves the problem and doesn’t hose up my calendar. Cheers.

**Comment by cakebarIO** [comment]
This task has been completed. When a user says "Alexa, tell QuickAdd to add [task] no date," specifically saying "no date," that [task] will be added to the user's Todoist Inbox without an auto-due-date of "today."

**Comment by bulawayo88** [comment]
This amazing. Waahoo! Thanks. Sorry that I couldn’t find the “buy me coffee” button.

**Comment by cakebarIO** [comment]
https://buymeacoffee.com/erikjohnrichter ...anything is appreciated! Thanks!
